local:
  enabled: True
  shot_capacity: 15
  alpha: 0.3  # weight to combine clip classifier and memory classifier
  beta: 6.0  # sample similarity multiplier, larger -> 1-NN
  gamma: 6.0  # entropy weighting for making prediction

## --- Global Cache Configuration ---
global:
  enabled: True
  shot_capacity: 12
  prototype: exp_weighted  # how to construct class prototype: mean, exp_weighted, min_ent
  gamma: 6.0  # entropy weighting for constructing prototypes